### ISSUE TITLE
Verify.js

### ISSUE THREAD

**Issue by aamirali1** [Pearson-Higher-Ed/component-archetype#1]
Do we need to add more verification checks like creating test scripts, usage of webpack, use of ES6 etc.

**Comment by aaronkaka** [comment]
I don't think we can mandate the use of webpack or ES6, as the dev may be more comfortable with browserify and ES5... this just gives them a good starting point for what we recommend.

As for tests, analysis via Sonar is probably going to be the way to verify code coverage.
