### ISSUE TITLE
Add name-replace to documentation?

### ISSUE THREAD

**Issue by StommePoes** [Pearson-Higher-Ed/component-archetype#2]
After following the README instructions, I still had in my new fake component a file appearing called dev.component-name.js and a few other places.

In Origami component-blueprint there's some text in the readme for finding all instances of "component-blueprint" or similar and changing them to the new name of your component. There was also a block on write-access on that repo because according to Adam or Drew, people would still forget what they were doing and push there (hopefully setting the new remote origin step won't be skipped). But so when this goes live, allowing only push access to PDA members would be a good idea.

**Comment by aaronkaka** [comment]
Yep, definitely have the block on write-access in place already.

I tried to limit the number of places where a dev would have to customize any naming. I will try to spell out more - it is only in the webpack config (as you mentioned about component-name), and main.js.

**Comment by StommePoes** [comment]
Ok, if it's not in so many places then people can decide their own search and replace.
